---
title: "keerthana"
date: 2020-11-01
---
title: Hello World
author: keerthana
email: keerthisaivel001@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  this i my new blog. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
